---
title: "Regressao linear simples"
# subtitle: "Sous-titre"
author: "Embrapa Arroz e Feijão"
date: "`r format(Sys.time(), '%d %B, %Y')`"
# toc: true
---

# Sua data

```{r, echo = input$echo}
extract <- function(text) {
  text <- gsub(" ", "", text)
  split <- strsplit(text, ",", fixed = FALSE)[[1]]
  as.numeric(split)
}

# Data output
y <- extract(input$y)
x <- extract(input$x)
dat <- data.frame(x, y)
kable(dat)

if (anyNA(x) | length(x) < 2 | anyNA(y) | length(y) < 2) {
  "Invalid input or not enough observations"
} else if (length(x) != length(y)) {
  "Number of observations must be equal for x and y"
} else {
  withMathJax(
    paste0("\\(\\bar{x} =\\) ", round(mean(x), 3)),
    br(),
    paste0("\\(\\bar{y} =\\) ", round(mean(y), 3)),
    br(),
    paste0("\\(n =\\) ", length(x))
  )
}
```

# Parametros computados a mao

```{r, echo = input$echo}
fit <- lm(y ~ x)
withMathJax(paste0(
  "\\(\\hat{\\beta}_1 = \\dfrac{\\big(\\sum^n_{i = 1} x_i y_i \\big) - n
                   \\bar{x} \\bar{y}}{\\sum^n_{i = 1} (x_i - \\bar{x})^2} = \\) ",
  round(fit$coef[[2]], 3)
))
```

```{r, echo = input$echo}
withMathJax(paste0(
  "\\(\\hat{\\beta}_0 = \\bar{y} - \\hat{\\beta}_1 \\bar{x} = \\) ",
  round(fit$coef[[1]], 3)
))
```

```{r, echo = input$echo}
withMathJax(paste0(
  "\\( \\Rightarrow y = \\hat{\\beta}_0 + \\hat{\\beta}_1 x = \\) ",
  round(fit$coef[[1]], 3), " + ", round(fit$coef[[2]], 3), "\\( x \\)"
))
```

# Parâmetros de cálculo em R

```{r, echo = input$echo}
summary(fit)
```

# Gráfico de regressão

```{r, echo = input$echo, warning = FALSE}
withMathJax(paste0(
  "Adj. \\( R^2 = \\) ", round(summary(fit)$adj.r.squared, 3),
  ", \\( \\beta_0 = \\) ", round(fit$coef[[1]], 3),
  ", \\( \\beta_1 = \\) ", round(fit$coef[[2]], 3),
  ", P-value ", "\\( = \\) ", signif(summary(fit)$coef[2, 4], 3)
))
```

```{r, echo = input$echo}
ggplot(dat, aes(x = x, y = y)) +
  geom_point() +
  stat_smooth(method = "lm", se = input$se) +
  ylab(input$ylab) +
  xlab(input$xlab) +
  theme_minimal()
```

# Interpretação

```{r, echo = input$echo, warning = FALSE}
if (summary(fit)$coefficients[1, 4] < 0.05 & summary(fit)$coefficients[2, 4] < 0.05) {
  withMathJax(
    paste0("(Certifique-se de que as suposições para regressão linear (independência, linearidade, normalidade e homocedasticidade) sejam atendidas antes de interpretar os coeficientes.)"),
    br(),
    paste0("Para um valor (hipotético) de ", input$xlab, "= 0, a média de", input$ylab, " = ", round(fit$coef[[1]], 3), "."),
    br(),
    paste0("Por um aumento de uma unidade de ", input$xlab, ", ", input$ylab, ifelse(round(fit$coef[[2]], 3) >= 0, " aumenta (em média) em ", " diminui (em média) em "), abs(round(fit$coef[[2]], 3)), ifelse(abs(round(fit$coef[[2]], 3)) >= 2, " unidades", " unit"), ".")
  )
} else if (summary(fit)$coefficients[1, 4] < 0.05 & summary(fit)$coefficients[2, 4] >= 0.05) {
  withMathJax(
    paste0("(Certifique-se de que as suposições para regressão linear (independência, linearidade, normalidade e homocedasticidade) sejam atendidas antes de interpretar os coeficientes.)"),
    br(),
    paste0("Para um valor (hipotético) de", input$xlab, "= 0, a média de", input$ylab, " = ", round(fit$coef[[1]], 3), "."),
    br(),
    paste0("\\( \\beta_1 \\)", " não é significativamente diferente de 0 (valor p = ", round(summary(fit)$coefficients[2, 4], 3), " ), portanto, não há relação significativa entre ", input$xlab, " e ", input$ylab, ".")
  )
} else if (summary(fit)$coefficients[1, 4] >= 0.05 & summary(fit)$coefficients[2, 4] < 0.05) {
  withMathJax(
    paste0("(Certifique-se de que as suposições para regressão linear (independência, linearidade, normalidade e homocedasticidade) sejam atendidas antes de interpretar os coeficientes.)"),
    br(),
    paste0("\\( \\beta_0 \\)", "não é significativamente diferente de 0 (valor p =", round(summary(fit)$coefficients[1, 4], 3)," ) então quando ", input$xlab, "
= 0, a média de ", input$ylab, " não é significativamente diferente de 0. "),
    br(),
    paste0("Por um aumento de uma unidade de", input$xlab, ", ", input$ylab, ifelse(round(fit$coef[[2]], 3) >= 0, " aumenta (em média) em "," diminui (em média) em "), abs(round(fit$coef[[2]], 3)), ifelse(abs(round(fit$coef[[2]], 3)) >= 2, " unidades ", " unit"), ".")
  )
} else {
  withMathJax(
    paste0("(Certifique-se de que as suposições para regressão linear (independência, linearidade, normalidade e homocedasticidade) sejam atendidas antes de interpretar os coeficientes.)"),
    br(),
    paste0("\\( \\beta_0 \\)", " e ", "\\( \\beta_1 \\)", " não são significativamente diferentes de 0 (valores-p = ", round(summary(fit)$coefficients[1, 4], 3), " e ", round(summary(fit)$coefficients[2, 4], 3),", respectivamente) então a média de ", input$ylab, " não é significativamente diferente de 0. ")
  )
}
```

